# # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   ╔╦╗╦═╗╔═╗╦  ╦╦╔═╗ ┬ ┬┌┬┐┬                           #
#    ║ ╠╦╝╠═╣╚╗╔╝║╚═╗ └┬┘││││                           #
#  o ╩ ╩╚═╩ ╩ ╚╝ ╩╚═╝o ┴ ┴ ┴┴─┘                         #
#                                                       #
# This file configures Travis CI.                       #
# (i.e. how we run the tests... mainly)                 #
#                                                       #
# https://docs.travis-ci.com/user/customizing-the-build #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

matrix:
    include:
        - addons:
             mariadb: 5.5
          node_js: '5'
        - addons:
             mariadb: 10.0
          node_js: '5'
        - addons:
             mariadb: 10.1
          node_js: '5'
        - addons:
             mariadb: 5.5
          node_js: '4'
        - addons:
             mariadb: 10.0
          node_js: '4'
        - addons:
             mariadb: 10.1
          node_js: '4'
branches:
  only:
    - master

services: mysql
sudo: false
before_script:
  - mysql -e 'create database adapter_tests;'
env:
  - WATERLINE_ADAPTER_TESTS_HOST=127.0.0.1 WATERLINE_ADAPTER_TESTS_USER=root WATERLINE_ADAPTER_TESTS_PASSWORD='' WATERLINE_ADAPTER_TESTS_DATABASE=adapter_tests
notifications:
  email:
    - ci@sailsjs.com
